spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook
    username: postgres
    password: EiH39LzSyQQn-Hz
    driver-class-name: org.postgresql.Driver

//TODO:
  #Before launching this application. Store the username and password as environment variables
  #On the intented host system for secure deployment

